<?php

use Illuminate\Database\Seeder;

class AjoutPays extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array();
        $data[] = array('idPays'=>'AF','nom'=>'Afghanistan');
		$data[] = array('idPays'=>'ZA','nom'=>'Afrique du Sud');
		$data[] = array('idPays'=>'AX','nom'=>'Åland, Îles');
		$data[] = array('idPays'=>'AL','nom'=>'Albanie');
		$data[] = array('idPays'=>'DZ','nom'=>'Algérie');
		$data[] = array('idPays'=>'DE','nom'=>'Allemagne');
		$data[] = array('idPays'=>'AD','nom'=>'Andorre');
		$data[] = array('idPays'=>'AO','nom'=>'Angola');
		$data[] = array('idPays'=>'AI','nom'=>'Anguilla');
		$data[] = array('idPays'=>'AQ','nom'=>'Antarctique');
		$data[] = array('idPays'=>'AG','nom'=>'Antigua et Barbuda');
		$data[] = array('idPays'=>'SA','nom'=>'Arabie Saoudite');
		$data[] = array('idPays'=>'AR','nom'=>'Argentine');
		$data[] = array('idPays'=>'AM','nom'=>'Arménie');
		$data[] = array('idPays'=>'AW','nom'=>'Aruba');
		$data[] = array('idPays'=>'AU','nom'=>'Australie');
		$data[] = array('idPays'=>'AT','nom'=>'Autriche');
		$data[] = array('idPays'=>'AZ','nom'=>'Azerbaïdjan');
		$data[] = array('idPays'=>'BS','nom'=>'Bahamas');
		$data[] = array('idPays'=>'BH','nom'=>'Bahrein');
		$data[] = array('idPays'=>'BD','nom'=>'Bangladesh');
		$data[] = array('idPays'=>'BB','nom'=>'Barbade');
		$data[] = array('idPays'=>'BY','nom'=>'Bélarus');
		$data[] = array('idPays'=>'BE','nom'=>'Belgique');
		$data[] = array('idPays'=>'BZ','nom'=>'Bélize');
		$data[] = array('idPays'=>'BJ','nom'=>'Bénin');
		$data[] = array('idPays'=>'BM','nom'=>'Bermudes');
		$data[] = array('idPays'=>'BT','nom'=>'Bhoutan');
		$data[] = array('idPays'=>'BO','nom'=>'Bolivie (État plurinational de)');
		$data[] = array('idPays'=>'BQ','nom'=>'Bonaire, Saint-Eustache et Saba');
		$data[] = array('idPays'=>'BA','nom'=>'Bosnie-Herzégovine');
		$data[] = array('idPays'=>'BW','nom'=>'Botswana');
		$data[] = array('idPays'=>'BV','nom'=>'Bouvet, Ile');
		$data[] = array('idPays'=>'BR','nom'=>'Brésil');
		$data[] = array('idPays'=>'BN','nom'=>'Brunéi Darussalam');
		$data[] = array('idPays'=>'BG','nom'=>'Bulgarie');
		$data[] = array('idPays'=>'BF','nom'=>'Burkina Faso');
		$data[] = array('idPays'=>'BI','nom'=>'Burundi');
		$data[] = array('idPays'=>'CV','nom'=>'Cabo Verde');
		$data[] = array('idPays'=>'KY','nom'=>'Caïmans, Iles');
		$data[] = array('idPays'=>'KH','nom'=>'Cambodge');
		$data[] = array('idPays'=>'CM','nom'=>'Cameroun');
		$data[] = array('idPays'=>'CA','nom'=>'Canada');
		$data[] = array('idPays'=>'CL','nom'=>'Chili');
		$data[] = array('idPays'=>'CN','nom'=>'Chine');
		$data[] = array('idPays'=>'CX','nom'=>'Christmas, île');
		$data[] = array('idPays'=>'CY','nom'=>'Chypre');
		$data[] = array('idPays'=>'CC','nom'=>'Cocos/Keeling (Îles)');
		$data[] = array('idPays'=>'CO','nom'=>'Colombie');
		$data[] = array('idPays'=>'KM','nom'=>'Comores');
		$data[] = array('idPays'=>'CG','nom'=>'Congo');
		$data[] = array('idPays'=>'CD','nom'=>'Congo, République démocratique du');
		$data[] = array('idPays'=>'CK','nom'=>'Cook, Iles');
		$data[] = array('idPays'=>'KR','nom'=>'Corée, République de');
		$data[] = array('idPays'=>'KP','nom'=>'Corée, République populaire démocratique de');
		$data[] = array('idPays'=>'CR','nom'=>'Costa Rica');
		$data[] = array('idPays'=>'CI','nom'=>'Côte d\'Ivoire');
		$data[] = array('idPays'=>'HR','nom'=>'Croatie');
		$data[] = array('idPays'=>'CU','nom'=>'Cuba');
		$data[] = array('idPays'=>'CW','nom'=>'Curaçao');
		$data[] = array('idPays'=>'DK','nom'=>'Danemark');
		$data[] = array('idPays'=>'DJ','nom'=>'Djibouti');
		$data[] = array('idPays'=>'DO','nom'=>'Dominicaine, République');
		$data[] = array('idPays'=>'DM','nom'=>'Dominique');
		$data[] = array('idPays'=>'EG','nom'=>'Egypte');
		$data[] = array('idPays'=>'SV','nom'=>'El Salvador');
		$data[] = array('idPays'=>'AE','nom'=>'Emirats arabes unis');
		$data[] = array('idPays'=>'EC','nom'=>'Equateur');
		$data[] = array('idPays'=>'ER','nom'=>'Erythrée');
		$data[] = array('idPays'=>'ES','nom'=>'Espagne');
		$data[] = array('idPays'=>'EE','nom'=>'Estonie');
		$data[] = array('idPays'=>'US','nom'=>'Etats-Unis d\'Amérique');
		$data[] = array('idPays'=>'ET','nom'=>'Ethiopie');
		$data[] = array('idPays'=>'FK','nom'=>'Falkland/Malouines (Îles)');
		$data[] = array('idPays'=>'FO','nom'=>'Féroé, îles');
		$data[] = array('idPays'=>'FJ','nom'=>'Fidji');
		$data[] = array('idPays'=>'FI','nom'=>'Finlande');
		$data[] = array('idPays'=>'FR','nom'=>'France');
		$data[] = array('idPays'=>'GA','nom'=>'Gabon');
		$data[] = array('idPays'=>'GM','nom'=>'Gambie');
		$data[] = array('idPays'=>'GE','nom'=>'Géorgie');
		$data[] = array('idPays'=>'GS','nom'=>'Géorgie du sud et les îles Sandwich du sud');
		$data[] = array('idPays'=>'GH','nom'=>'Ghana');
		$data[] = array('idPays'=>'GI','nom'=>'Gibraltar');
		$data[] = array('idPays'=>'GR','nom'=>'Grèce');
		$data[] = array('idPays'=>'GD','nom'=>'Grenade');
		$data[] = array('idPays'=>'GL','nom'=>'Groenland');
		$data[] = array('idPays'=>'GP','nom'=>'Guadeloupe');
		$data[] = array('idPays'=>'GU','nom'=>'Guam');
		$data[] = array('idPays'=>'GT','nom'=>'Guatemala');
		$data[] = array('idPays'=>'GG','nom'=>'Guernesey');
		$data[] = array('idPays'=>'GN','nom'=>'Guinée');
		$data[] = array('idPays'=>'GW','nom'=>'Guinée-Bissau');
		$data[] = array('idPays'=>'GQ','nom'=>'Guinée équatoriale');
		$data[] = array('idPays'=>'GY','nom'=>'Guyana');
		$data[] = array('idPays'=>'GF','nom'=>'Guyane française');
		$data[] = array('idPays'=>'HT','nom'=>'Haïti');
		$data[] = array('idPays'=>'HN','nom'=>'Honduras');
		$data[] = array('idPays'=>'HK','nom'=>'Hong Kong');
		$data[] = array('idPays'=>'HU','nom'=>'Hongrie');
		$data[] = array('idPays'=>'IM','nom'=>'Île de Man');
		$data[] = array('idPays'=>'UM','nom'=>'Îles mineures éloignées des Etats-Unis');
		$data[] = array('idPays'=>'VG','nom'=>'Îles vierges britanniques');
		$data[] = array('idPays'=>'VI','nom'=>'Îles vierges des Etats-Unis');
		$data[] = array('idPays'=>'IN','nom'=>'Inde');
		$data[] = array('idPays'=>'IO','nom'=>'Indien (Territoire britannique de l\'océan)');
		$data[] = array('idPays'=>'ID','nom'=>'Indonésie');
		$data[] = array('idPays'=>'IR','nom'=>'Iran');
		$data[] = array('idPays'=>'IQ','nom'=>'Iraq');
		$data[] = array('idPays'=>'IE','nom'=>'Irlande');
		$data[] = array('idPays'=>'IS','nom'=>'Islande');
		$data[] = array('idPays'=>'IL','nom'=>'Israël');
		$data[] = array('idPays'=>'IT','nom'=>'Italie');
		$data[] = array('idPays'=>'JM','nom'=>'Jamaïque');
		$data[] = array('idPays'=>'JP','nom'=>'Japon');
		$data[] = array('idPays'=>'JE','nom'=>'Jersey');
		$data[] = array('idPays'=>'JO','nom'=>'Jordanie');
		$data[] = array('idPays'=>'KZ','nom'=>'Kazakhstan');
		$data[] = array('idPays'=>'KE','nom'=>'Kenya');
		$data[] = array('idPays'=>'KG','nom'=>'Kirghizistan');
		$data[] = array('idPays'=>'KI','nom'=>'Kiribati');
		$data[] = array('idPays'=>'KW','nom'=>'Koweït');
		$data[] = array('idPays'=>'LA','nom'=>'Lao');
		$data[] = array('idPays'=>'LS','nom'=>'Lesotho');
		$data[] = array('idPays'=>'LV','nom'=>'Lettonie');
		$data[] = array('idPays'=>'LB','nom'=>'Liban');
		$data[] = array('idPays'=>'LR','nom'=>'Libéria');
		$data[] = array('idPays'=>'LY','nom'=>'Libye');
		$data[] = array('idPays'=>'LI','nom'=>'Liechtenstein');
		$data[] = array('idPays'=>'LT','nom'=>'Lituanie');
		$data[] = array('idPays'=>'LU','nom'=>'Luxembourg');
		$data[] = array('idPays'=>'MO','nom'=>'Macao');
		$data[] = array('idPays'=>'MK','nom'=>'Macédoine');
		$data[] = array('idPays'=>'MG','nom'=>'Madagascar');
		$data[] = array('idPays'=>'MY','nom'=>'Malaisie');
		$data[] = array('idPays'=>'MW','nom'=>'Malawi');
		$data[] = array('idPays'=>'MV','nom'=>'Maldives');
		$data[] = array('idPays'=>'ML','nom'=>'Mali');
		$data[] = array('idPays'=>'MT','nom'=>'Malte');
		$data[] = array('idPays'=>'MA','nom'=>'Maroc');
		$data[] = array('idPays'=>'MH','nom'=>'Marshall, Iles');
		$data[] = array('idPays'=>'MQ','nom'=>'Martinique');
		$data[] = array('idPays'=>'MU','nom'=>'Maurice');
		$data[] = array('idPays'=>'MR','nom'=>'Mauritanie');
		$data[] = array('idPays'=>'YT','nom'=>'Mayotte');
		$data[] = array('idPays'=>'MX','nom'=>'Mexique');
		$data[] = array('idPays'=>'FM','nom'=>'Micronésie');
		$data[] = array('idPays'=>'MD','nom'=>'Moldova');
		$data[] = array('idPays'=>'MC','nom'=>'Monaco');
		$data[] = array('idPays'=>'MN','nom'=>'Mongolie');
		$data[] = array('idPays'=>'ME','nom'=>'Monténégro');
		$data[] = array('idPays'=>'MS','nom'=>'Montserrat');
		$data[] = array('idPays'=>'MZ','nom'=>'Mozambique');
		$data[] = array('idPays'=>'MM','nom'=>'Myanmar');
		$data[] = array('idPays'=>'NA','nom'=>'Namibie');
		$data[] = array('idPays'=>'NR','nom'=>'Nauru');
		$data[] = array('idPays'=>'NP','nom'=>'Népal');
		$data[] = array('idPays'=>'NI','nom'=>'Nicaragua');
		$data[] = array('idPays'=>'NE','nom'=>'Niger');
		$data[] = array('idPays'=>'NG','nom'=>'Nigéria');
		$data[] = array('idPays'=>'NU','nom'=>'Niue');
		$data[] = array('idPays'=>'NF','nom'=>'Norfolk, Ile');
		$data[] = array('idPays'=>'NO','nom'=>'Norvège');
		$data[] = array('idPays'=>'NC','nom'=>'Nouvelle-Calédonie');
		$data[] = array('idPays'=>'NZ','nom'=>'Nouvelle-Zélande');
		$data[] = array('idPays'=>'OM','nom'=>'Oman');
		$data[] = array('idPays'=>'UG','nom'=>'Ouganda');
		$data[] = array('idPays'=>'UZ','nom'=>'Ouzbékistan');
		$data[] = array('idPays'=>'PK','nom'=>'Pakistan');
		$data[] = array('idPays'=>'PW','nom'=>'Palaos');
		$data[] = array('idPays'=>'PS','nom'=>'Palestine, Etat de');
		$data[] = array('idPays'=>'PA','nom'=>'Panama');
		$data[] = array('idPays'=>'PG','nom'=>'Papouasie-Nouvelle-Guinée');
		$data[] = array('idPays'=>'PY','nom'=>'Paraguay');
		$data[] = array('idPays'=>'NL','nom'=>'Pays-Bas');
		$data[] = array('idPays'=>'XX','nom'=>'Pays inconnu');
		$data[] = array('idPays'=>'ZZ','nom'=>'Pays multiples');
		$data[] = array('idPays'=>'PE','nom'=>'Pérou');
		$data[] = array('idPays'=>'PH','nom'=>'Philippines');
		$data[] = array('idPays'=>'PN','nom'=>'Pitcairn');
		$data[] = array('idPays'=>'PL','nom'=>'Pologne');
		$data[] = array('idPays'=>'PF','nom'=>'Polynésie française');
		$data[] = array('idPays'=>'PR','nom'=>'Porto Rico');
		$data[] = array('idPays'=>'PT','nom'=>'Portugal');
		$data[] = array('idPays'=>'QA','nom'=>'Qatar');
		$data[] = array('idPays'=>'SY','nom'=>'République arabe syrienne');
		$data[] = array('idPays'=>'CF','nom'=>'République centrafricaine');
		$data[] = array('idPays'=>'RE','nom'=>'Réunion');
		$data[] = array('idPays'=>'RO','nom'=>'Roumanie');
		$data[] = array('idPays'=>'GB','nom'=>'Royaume-Uni de Grande-Bretagne et d\'Irlande du Nord');
		$data[] = array('idPays'=>'RU','nom'=>'Russie');
		$data[] = array('idPays'=>'RW','nom'=>'Rwanda');
		$data[] = array('idPays'=>'EH','nom'=>'Sahara occidental');
		$data[] = array('idPays'=>'BL','nom'=>'Saint-Barthélemy');
		$data[] = array('idPays'=>'KN','nom'=>'Saint-Kitts-et-Nevis');
		$data[] = array('idPays'=>'SM','nom'=>'Saint-Marin');
		$data[] = array('idPays'=>'PM','nom'=>'Saint-Pierre-et-Miquelon');
		$data[] = array('idPays'=>'VC','nom'=>'Saint-Vincent-et-les-Grenadines');
		$data[] = array('idPays'=>'SH','nom'=>'Sainte-Hélène, Ascension et Tristan da Cunha');
		$data[] = array('idPays'=>'LC','nom'=>'Sainte-Lucie');
		$data[] = array('idPays'=>'SB','nom'=>'Salomon, Iles');
		$data[] = array('idPays'=>'WS','nom'=>'Samoa');
		$data[] = array('idPays'=>'AS','nom'=>'Samoa américaines');
		$data[] = array('idPays'=>'ST','nom'=>'Sao Tomé-et-Principe');
		$data[] = array('idPays'=>'SN','nom'=>'Sénégal');
		$data[] = array('idPays'=>'RS','nom'=>'Serbie');
		$data[] = array('idPays'=>'SC','nom'=>'Seychelles');
		$data[] = array('idPays'=>'SL','nom'=>'Sierra Leone');
		$data[] = array('idPays'=>'SG','nom'=>'Singapour');
		$data[] = array('idPays'=>'SK','nom'=>'Slovaquie');
		$data[] = array('idPays'=>'SI','nom'=>'Slovénie');
		$data[] = array('idPays'=>'SO','nom'=>'Somalie');
		$data[] = array('idPays'=>'SD','nom'=>'Soudan');
		$data[] = array('idPays'=>'SS','nom'=>'Soudan du Sud');
		$data[] = array('idPays'=>'LK','nom'=>'Sri Lanka');
		$data[] = array('idPays'=>'SE','nom'=>'Suède');
		$data[] = array('idPays'=>'CH','nom'=>'Suisse');
		$data[] = array('idPays'=>'SR','nom'=>'Suriname');
		$data[] = array('idPays'=>'SJ','nom'=>'Svalbard et île Jan Mayen');
		$data[] = array('idPays'=>'SZ','nom'=>'Swaziland');
		$data[] = array('idPays'=>'TJ','nom'=>'Tadjikistan');
		$data[] = array('idPays'=>'TW','nom'=>'Taïwan, Province de Chine');
		$data[] = array('idPays'=>'TZ','nom'=>'Tanzanie, République unie de');
		$data[] = array('idPays'=>'TD','nom'=>'Tchad');
		$data[] = array('idPays'=>'CZ','nom'=>'Tchèque, République');
		$data[] = array('idPays'=>'TF','nom'=>'Terres australes françaises');
		$data[] = array('idPays'=>'TH','nom'=>'Thaïlande');
		$data[] = array('idPays'=>'TL','nom'=>'Timor-Leste');
		$data[] = array('idPays'=>'TG','nom'=>'Togo');
		$data[] = array('idPays'=>'TK','nom'=>'Tokelau');
		$data[] = array('idPays'=>'TO','nom'=>'Tonga');
		$data[] = array('idPays'=>'TT','nom'=>'Trinité-et-Tobago');
		$data[] = array('idPays'=>'TN','nom'=>'Tunisie');
		$data[] = array('idPays'=>'TM','nom'=>'Turkménistan');
		$data[] = array('idPays'=>'TC','nom'=>'Turks-et-Caïcos (Îles)');
		$data[] = array('idPays'=>'TR','nom'=>'Turquie');
		$data[] = array('idPays'=>'TV','nom'=>'Tuvalu');
		$data[] = array('idPays'=>'UA','nom'=>'Ukraine');
		$data[] = array('idPays'=>'UY','nom'=>'Uruguay');
		$data[] = array('idPays'=>'VU','nom'=>'Vanuatu');
		$data[] = array('idPays'=>'VA','nom'=>'Vatican : voir Saint-Siè');
		$data[] = array('idPays'=>'VE','nom'=>'Venezuela (République bolivarienne du)');
		$data[] = array('idPays'=>'VN','nom'=>'Viet Nam');
		$data[] = array('idPays'=>'WF','nom'=>'Wallis et Futuna');
		$data[] = array('idPays'=>'YE','nom'=>'Yémen');
		$data[] = array('idPays'=>'ZM','nom'=>'Zambie');
		$data[] = array('idPays'=>'ZW','nom'=>'Zimbabwe');

		DB::table('pays')->insert($data);

    }
}
